import { StyleSheet } from 'react-native';

const ink = '#1C2028';
const lime = '#B6D87A';
const muted = '#747781';
export const styles = StyleSheet.create({
  pharmacyFilters: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  pharmacyChip: { flexDirection: 'row', alignItems: 'center', gap: 7, minHeight: 44, paddingHorizontal: 13, borderRadius: 22, borderWidth: 1, borderColor: '#DDE5D2', backgroundColor: '#FFFFFF' },
  pharmacyChipActive: { backgroundColor: '#526D34', borderColor: '#526D34' },
  pharmacyChipText: { fontSize: 12, fontWeight: '600', color: '#63764D' },
  pharmacyChipTextActive: { color: '#F5F8EF' },
  root: { flex: 1, backgroundColor: '#F5F7EF' },
  page: { padding: 18, paddingTop: 22, gap: 22, width: '100%', maxWidth: 1360, alignSelf: 'center', paddingBottom: 150 },
  mobileDock: { position:'absolute', left:14, right:14, bottom:16, gap:8 },
  bottomNav: {flexDirection:'row',justifyContent:'space-around',backgroundColor:'#FFFFFF',padding:9,borderRadius: 30,borderWidth: 1,borderColor: '#E5E9DD'},
  navItem: {flex:1,minHeight:56,alignItems:'center',justifyContent:'center',gap:4},
  navIcon: {width:46,height:38,alignItems:'center',justifyContent:'center',borderRadius: 12},
  navIconActive: {backgroundColor:'#7B9D47'},
  purchaseSwitch: { flexDirection:'row', padding:5, gap:4, borderRadius: 12, backgroundColor:'#FFFFFF', borderWidth: 1, borderColor: '#E0E5E7' },
  purchaseTab: { flex:1, minHeight:48, alignItems:'center', justifyContent:'center', paddingHorizontal:10, borderRadius: 12 },
  purchaseTabActive: { backgroundColor:'#1C2028' },
  purchaseTabText: { color:'#747781', fontSize:14, fontWeight:'500' },
  purchaseTabTextActive: { color:'#FFFFFF' },
  cartDot: {position:'absolute',right:7,top:3,width:7,height:7,borderRadius:4,backgroundColor:'#8B5BB3'},
  cartDock: {flexDirection:'row',justifyContent:'space-between',backgroundColor:'#1C2028',padding:16,borderRadius: 12},
  cartDockText: {color:'#00BFA9',fontSize:14,fontWeight:'600'},
  searchRow: {position:'relative'},
  searchInput: {paddingRight:50},
  clearSearch: {position:'absolute',right:3,top:3,bottom:3,width:44,alignItems:'center',justifyContent:'center',zIndex:3},
  clearText: {fontSize:24,color:'#1C2028'},
  chartToggle: {flexDirection:'row',alignItems:'center',justifyContent:'space-between',minHeight:56,paddingHorizontal:18,borderRadius: 12,backgroundColor:'#F4F5F7'},
  pageWide: { paddingHorizontal: 48, paddingTop: 36, gap: 36 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 12 },
  brand: { flexDirection: 'row', gap: 10, alignItems: 'center' },
  emblem: { width: 42, height: 42, borderRadius: 15, backgroundColor: ink, alignItems: 'center', justifyContent: 'center' },
  crossH: { position: 'absolute', width: 23, height: 8, borderRadius: 2, backgroundColor: lime },
  crossV: { position: 'absolute', width: 8, height: 23, borderRadius: 2, backgroundColor: lime },
  title: { fontSize: 22, letterSpacing: -.7, fontWeight: '600', color: ink },
  brandCaption: { fontSize: 9, letterSpacing: 2.6, fontWeight: '700', color: muted, marginTop: 3 },
  headerSymbol: { width: 42, height: 42, borderRadius: 12, borderWidth: 1, borderColor: '#E0E5E7', alignItems: 'center', justifyContent: 'center' },
  headerSymbolText: { fontSize: 23, color: ink },
  muted: { color: muted, fontSize: 13, lineHeight: 20 },
  tabs: { flexGrow: 0 },
  tab: { paddingHorizontal: 20, paddingVertical: 14, borderRadius: 12, marginRight: 6 },
  activeTab: { backgroundColor: ink },
  activeTabText: { color: lime },
  tabText: { color: muted, fontWeight: '600', fontSize: 13 },
  authLayout: { gap: 28 },
  authLayoutWide: { flexDirection: 'row', gap: 56, alignItems: 'center' },
  welcome: { backgroundColor: ink, borderRadius: 12, padding: 26, minHeight: 305, overflow: 'hidden' },
  welcomeWide: { flex: 1.15, minHeight: 600, padding: 42, borderRadius: 12 },
  welcomeTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', zIndex: 2 },
  statusDot: { width: 7, height: 7, borderRadius: 5, backgroundColor: lime },
  welcomeTitle: { color: '#20232A', fontSize: 46, lineHeight: 47, letterSpacing: -2.4, fontWeight: '700', marginTop: 25, zIndex: 2 },
  welcomeTitleWide: { fontSize: 76, lineHeight: 77, letterSpacing: -4, marginTop: 42 },
  limeText: { color: lime },
  welcomeBottom: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 'auto', paddingTop: 20 },
  decorLine: { height: 1, width: 45, backgroundColor: '#78836F' },
  welcomePlus: { color: lime, fontSize: 26, fontWeight: '300' },
  art: { position: 'absolute', width: 240, height: 300, right: -36, bottom: -33, transform: [{ rotate: '28deg' }] },
  narrowArt: { right: -105, bottom: -110 },
  orbit: { position: 'absolute', width: 230, height: 230, borderWidth: 1, borderColor: '#63744A', borderRadius: 150, top: 30, left: 0 },
  capsule: { width: 94, height: 208, position: 'absolute', top: 20, left: 78, borderRadius: 60, overflow: 'hidden', borderWidth: 1, borderColor: '#D3D8DF' },
  capsuleTop: { flex: 1, backgroundColor: lime, overflow: 'hidden' },
  capsuleBottom: { flex: 1, backgroundColor: '#F5F6F8', borderTopWidth: 2, borderColor: '#D3D8DF', alignItems: 'center', justifyContent: 'center' },
  capsuleShine: { width: 9, height: 85, borderRadius: 12, backgroundColor: '#BDFFF4', position: 'absolute', left: 14, top: 14, opacity: 0 },
  capsuleMark: { width: 28, height: 4, backgroundColor: '#A6AFB9', borderRadius: 3 },
  artSpark: { position: 'absolute', right: 18, top: 0 },
  artSparkText: { fontSize: 43, color: '#E3ECCB' },
  smallArt: { width: 180, height: 150, transform: [{ rotate: '35deg' }] },
  smallOrbit: { width: 142, height: 142, top: 4, left: 18, borderColor: 'transparent' },
  smallCapsule: { width: 62, height: 126, left: 58, top: 12 },
  authCard: { gap: 15, paddingHorizontal: 5, paddingVertical: 5 },
  authCardWide: { flex: .85, maxWidth: 440, paddingRight: 12 },
  authHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 },
  authTitle: { color: ink, fontSize: 35, fontWeight: '600', letterSpacing: -1.7 },
  authArrow: { fontSize: 35, color: '#89927C', fontWeight: '300' },
  scanButton: {width:54,height:54,borderRadius:19,backgroundColor:'#E8EEDC',alignItems:'center',justifyContent:'center'},
  catalogBanner: {padding:24,borderRadius:28,backgroundColor:'#E4EECD',flexDirection:'row',alignItems:'center',overflow:'hidden',minHeight:185},
  bannerAction: {alignSelf:'flex-start',paddingHorizontal:18,paddingVertical:11,backgroundColor:'#FFFFFF',borderRadius:24},
  bannerActionText: {fontSize:12,fontWeight:'600',color:'#4F6D2D'},
  bannerIcon: {width:94,height:120,borderRadius:48,backgroundColor:'#D3E4AD',alignItems:'center',justifyContent:'center',transform:[{rotate:'-22deg'}]},
  hero: { padding: 24, gap: 12, backgroundColor: '#E8F5F2', borderRadius: 12, borderWidth:1, borderColor:'#D5EAE5' },
  eyebrow: { letterSpacing: 2.2, fontSize: 10, fontWeight: '600', color: '#717680' },
  heroTitle: { fontSize: 27, lineHeight: 33, letterSpacing: -.8, fontWeight: '500', color: '#20232A', zIndex: 1 },
  heroArt: { width:'100%', marginVertical:-8 },
  input: { backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E0E5E7', borderRadius: 12, paddingHorizontal: 20, paddingVertical: 18, minHeight: 58, fontSize: 15, color: ink, zIndex: 1 },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 18 },
  card: { padding: 24, backgroundColor: '#FFFFFF', borderRadius: 12, gap: 16, borderWidth: 1, borderColor: '#E0E5E7' },
  product: { flexBasis: 255, flexGrow: 1, maxWidth: 420 },
  facilityIcon: { padding: 15, borderRadius: 12, backgroundColor: "#F8F9FA" },
  documentIcon: { padding: 16, alignSelf: "flex-start", borderRadius: 12, backgroundColor: "#F8F9FA" },
  facilityInitial: { fontSize: 28, fontWeight: "700", color: "#BBC1CB" },
  productArt: { height: 164, backgroundColor: '#F0F4F4', borderRadius: 12, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  heading: { fontSize: 19, letterSpacing: -.5, fontWeight: '600', color: ink },
  price: { fontSize: 26, letterSpacing: -1, fontWeight: '500', color: ink },
  badge: { color: '#17766D', fontSize: 11, alignSelf: 'flex-start', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 12, backgroundColor: '#E1F6F1' },
  button: { borderRadius: 12, backgroundColor: ink, paddingHorizontal: 23, paddingVertical: 16, minHeight: 50, justifyContent: 'center', alignItems: 'center', marginRight: 5 },
  secondary: { backgroundColor: '#FFFFFF', borderWidth:1, borderColor: '#E0E5E7' },
  secondaryText: { color: ink },
  buttonText: { color: '#F7F9FA', fontWeight: '600', fontSize: 14 },
  disabled: { opacity: .48 },
  pressed: { opacity: .72 },
  row: { flexDirection: 'row', alignItems: 'center', gap: 15 },
  message: { padding: 16, backgroundColor: '#F4E8C8', borderRadius: 16, color: '#624C23', fontSize: 14 },
  empty: { padding: 40, textAlign: 'center', color: muted, backgroundColor: '#F3F4F6', borderRadius: 12 },
});
